name: clang-format

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Use clang-format
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        clangFormatVersion: 11
        inplace: True

    - name: Push
      uses: EndBug/add-and-commit@v6.2.0
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
        token: ${{ secrets.GITHUB_TOKEN }}
