name: clang-format

on: [push,pull-request]
  # Sequence of patterns matched against refs/tags
tags:
  - v*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  format:
    name: "Format"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Use clang-format
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        clangFormatVersion: 11
        inplace: True

    - name: Push
      uses: EndBug/add-and-commit@v6.2.0
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
        token: ${{ secrets.GITHUB_TOKEN }}
