name: Windows MinGW

on:
    push:
    pull_request:
    schedule:
    #Every Sunday at midnight
    - cron:  '0 0 * * 0'

env:
  CMAKE_VERSION: 3.16.x
  NINJA_VERSION: 1.10.2
  BUILD_TYPE: Release
  CCACHE_VERSION: 3.7.7
  CC: gcc
  CXX: g++
  artifact: "Windows-MinGW.tar.xz"
  BUILDCACHE_VERSION: 0.23.0
  BUILDCACHE_DIR: ${{ github.workspace }}/buildcache_dir

jobs:
  # Checkout apply clang-format and upload artifact
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2

    - name: Use clang-format
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: '.'
        clangFormatVersion: 11
        inplace: True

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: clang-format
        path: ${{ github.workspace }}

  build:
    needs: format
    name: "Build"
    runs-on: windows-latest
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: clang-format

    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.6
      with:
        cmake-version: '${{env.CMAKE_VERSION}}'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
      with:
        version: '${{env.NINJA_VERSION}}'

    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        release: true
        update: true

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: "C:\ProgramData\chocolatey\bin"
        key: cache-deps

    - name: Install sudo
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install sudo

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1.0.2

    - name: Configure
      run: cmake -S ${{ github.workspace }} -G Ninja  -B build -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -D CMAKE_C_COMPILER_LAUNCHER=buildcache -D CMAKE_CXX_COMPILER_LAUNCHER=buildcache

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel 2

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} -j2 --verbose --output-on-failure

    - name: Install Strip
      run: cmake --install build --prefix instdir --strip

    - name: 📦 Pack
      working-directory: instdir
      run: cmake -E tar cJfv ../${{ env.artifact }} .

  release:
    name: "Release"
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 🔗 Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: instdir
        name: ${{ env.artifact }}

  publish:
    if: contains(github.ref, 'tags/v')
    name: "Publish"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: release

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.artifact }}
        path: ./

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./
    - id: set_upload_url
      run: |
        upload_url=`cat ./upload_url`
        echo ::set-output name=upload_url::$upload_url
    - name: Upload to Release
      id: upload_to_release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: ./${{ env.artifact }}
        asset_name: ${{ env.artifact }}
        asset_content_type: application/x-gtar
